ARG GOLANG_IMAGE=golang:1.20-alpine@sha256:d0edf023da755c2917ae42dd57e4f745d82c8c9ee0b510b4d3da2a80da11c230

FROM ${GOLANG_IMAGE} AS build
WORKDIR /src
ENV CGO_ENABLED=0
COPY go.* .
RUN go mod download
COPY . .
RUN go build -trimpath -ldflags "-s -w" -o /out/buildkit-tekton ./cmd/buildkit-tekton

FROM scratch
COPY --from=build /out/ /
LABEL moby.buildkit.frontend.network.none="true"
ENTRYPOINT ["/buildkit-tekton"]
