#syntax=ghcr.io/vdemeester/buildkit-tekton/frontend
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: golang-test-pipeline-run
spec:
  taskRef:
    name: git-clone
    bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.5
  params:
    - name: url
      value: https://github.com/vdemeester/go-helloworld-app
  workspaces:
    - name: output
      emptyDir: {}
