name: test

on:
  push:
    branches: [ main, 'release/**' ]
  pull_request:
    branches: [ main ]

jobs:

  test-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Install test dependencies"
      run: |
        sudo apt-get update
        sudo apt-get install -y moreutils make
    - name: "Run the integration test"
      run: ./hack/test.sh
    - name: "Show the local images"
      run: docker images --no-trunc
